#' This function is designed for the clustering the spots based on the spots-spots similarity
#'
#' The function is based on the non-spatial clustering method, Louvain's algorithm but with adaptive resolution setting
#'
#' @importFrom igraph graph_from_adjacency_matrix membership cluster_louvain
#'
#' @param Seurat.data the Seurat object generated by data_process.
#' @param similarity_mat a spots similarity matrix.
#' @param setting_k the number of clustering setting by users.
#' @param resolution_louvain setting the resolution for the algorithm. Provided by the user. Default setting is NULL.
#' @param max.res maximal resolution using for the selection of optimal resolution. Default setting is 5.
#' @param increase the interval between a series candidate resolution. Default setting is 0.05.
#'
#'
#' @export
#'


Louvain_clustering <- function(Seurat.data, similarity_mat, setting_k = 7,
                               resolution_louvain = NULL, max.res = 5, increase = 0.05){
  if(! isSymmetric(similarity_mat))
    stop("The constructed similarity matrix need be symmetric...")
  res_all <- seq(0.02, max.res, increase)

  net <- igraph::graph_from_adjacency_matrix(similarity_mat, mode = "undirected", weighted = TRUE)
  if(is.null(resolution_louvain)){
    k <- 1
    total_k <- length(res_all)
    records_1 <- c()
    records_2 <- matrix(0, nrow = total_k, ncol = nrow(similarity_mat))
    for (i in 1:length(res_all)) {
      # set.seed(2023)
      louvain_cluster.temp <- igraph::cluster_louvain(net, resolution = res_all[i])
      res <- igraph::membership(louvain_cluster.temp)
      records_1 <- c(records_1, length(levels(as.factor(res))))
      records_2[i,] <- res
      message(paste0("Louvain resolution: ", res_all[i], "  Number of clusters:", length(levels(as.factor(res)))))
      if(length(levels(as.factor(res))) == setting_k){
        message("Find appropriate resolution....")
        break
      }
      k <- k + 1
    }
    if(k >= total_k){
      message("Can't find comfortable resolution to get the number of clusters setting by users and we will set the resolution get the stablest results")
      dis_tmp <- abs(setting_k - as.numeric(levels(as.factor(records_1))))
      tmp1 <- table(records_1)[which(dis_tmp == min(dis_tmp))]
      most_cluster <- as.numeric(names(tmp1)[which(tmp1 == max(tmp1))])
      res <- records_2[min(which(records_1 == most_cluster)),]
      # most_cluster <- as.numeric(names(which(table(records_1) == max(table(records_1)))))
      # res <- records_2[min(which(records_1 == most_cluster)),]
    }
  }
  if(!is.null(resolution_louvain)){
    louvain_cluster <- igraph::cluster_louvain(net, resolution = resolution_louvain)
    res <- igraph::membership(louvain_cluster)
  }
  res.final <- res


  names(res.final) <- colnames(similarity_mat)
  return(res.final)
}
